### ISSUE TITLE
uc_mcontext struct

### ISSUE THREAD

**Issue by llllIIIllll** [lgeek/spec_poc_arm#2]
dump_sys_regs.c: In function ‘get_value’:
dump_sys_regs.c:113:17: error: ‘mcontext_t’ has no member named ‘pc’
  c->uc_mcontext.pc += 24;

**Comment by lgeek** [comment]
That's not much to go on. Based on only that, my best guess is that you're not compiling for AArch64. If it's not the case, please come back with more details about the build system.

**Comment by poooooooooooooi** [comment]
emmmm, i use AArch64 in AOSP.

**Comment by llllIIIllll** [comment]
I use AArch64 in AOSP and how to compile for AArch64.

**Comment by lgeek** [comment]
Don't know, I don't really do Android. I've built [a statically linked executable](https://github.com/lgeek/spec_poc_arm/releases/tag/180120) which should work on your device.

**Comment by lgeek** [comment]
I can confirm that executable runs on Android. I'm going to close this issue as there's been no followup.
